# Generated by Django 4.2.1 on 2023-05-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Бренд'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Продукты '},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.products')),
            ],
            options={
                'verbose_name_plural': 'Коментарий',
                'ordering': ['-create_data'],
            },
        ),
    ]
