# Generated by Django 4.2.1 on 2023-05-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_cart_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='descriptions_af',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ar_dz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ast',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_az',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_be',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_bg',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_bn',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_br',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_bs',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ca',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ckb',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_cs',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_cy',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_da',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_de',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_dsb',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_el',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_en_au',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_en_gb',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_eo',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_es_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_es_co',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_es_mx',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_es_ni',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_es_ve',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_et',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_eu',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_fa',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_fi',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_fy',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ga',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_gd',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_gl',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_he',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_hi',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_hr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_hsb',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_hu',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_hy',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ia',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ig',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ind',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_io',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_is',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_it',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ja',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ka',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_kab',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_kk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_km',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_kn',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ko',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ky',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_lb',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_lt',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_lv',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_mk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ml',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_mn',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_mr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ms',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_my',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_nb',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ne',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_nl',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_nn',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_os',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_pa',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_pl',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_pt',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_pt_br',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ro',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_sk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_sl',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_sq',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_sr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_sr_latn',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_sv',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_sw',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ta',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_te',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_tg',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_th',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_tk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_tr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_tt',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_udm',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_uk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_ur',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_vi',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_zh_hans',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='descriptions_zh_hant',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_af',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ar',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ar_dz',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ast',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_az',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_be',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_bg',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_bn',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_br',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_bs',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ca',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ckb',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_cs',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_cy',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_da',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_de',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_dsb',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_el',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_en_au',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_en_gb',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_eo',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_es',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_es_ar',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_es_co',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_es_mx',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_es_ni',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_es_ve',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_et',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_eu',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_fa',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_fi',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_fy',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ga',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_gd',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_gl',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_he',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_hi',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_hr',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_hsb',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_hu',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ia',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ig',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ind',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_io',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_is',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_it',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ja',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ka',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_kab',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_kk',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_km',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_kn',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ko',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ky',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_lb',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_lt',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_lv',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_mk',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ml',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_mn',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_mr',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ms',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_my',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_nb',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ne',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_nl',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_nn',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_os',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_pa',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_pl',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_pt',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_pt_br',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ro',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_sk',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_sl',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_sq',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_sr',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_sr_latn',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_sv',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_sw',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ta',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_te',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_tg',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_th',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_tk',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_tt',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_udm',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_uk',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ur',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_vi',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_zh_hans',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_zh_hant',
            field=models.CharField(max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_af',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ast',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_be',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_bg',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_bn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_bs',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_cy',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_da',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_el',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_eo',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_et',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_eu',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_fy',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ga',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_gd',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_gl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_hr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_hu',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ia',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ig',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ind',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_io',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_is',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_kab',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_km',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_kn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_lb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_lt',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_lv',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ml',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_mn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_mr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ms',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_my',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_nb',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_nn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_os',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_pa',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_sk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_sw',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ta',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_te',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_th',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_tk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_tt',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_udm',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ur',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
